### PR TITLE
CSS based hidden instead of JS toggle

### PR DESCRIPTION
**Pull request by algorys**
For better CSS integration, we need to know (with classes) if the body was displayed or not.
So we modifiied your script to toggle a class presence instead of the default jQuery.toggleVisible style

In hope, other (you?) find this useful, here the pull request.
Let me know if I need to change anything to fillfull contribution requirements.

### CODE REVIEW

**Comment by gturri** [comment]
Thank you for your interest in this plugin!

My main concern with this PR is that it would break the hiddenSwitch plugin (https://github.com/gturri/hiddenSwitch), which relies on this hidden plugin. (I guess if someone is motivated, it could be possible to adapt hiddenSwitch though)

Beside this, I have a few questions:
* Where do those icons come from (ie: is their license GPL compatible?)
* It seems to me (unless I mess up with a cache) that the look and feel is changed (eg: the `__background_alt__` color isn't used anymore). Is there a particular reason for this?

**Comment by algorys** [comment]
Just pushed modifications:

 * 5dedc0d to get back with `__background_alt__` and `__border__`
 * 39da856 My icons were from glyphicons which is CC licensed and not really GPL compatible. I modified to use [IcoMoon - icons packs](https://icomoon.io/#icons-icomoon) which is GPL licensed.
 * ffe9fc3 I integrated hiddenSwitch plugin into this one, hiddenSwitch plugin is not needed anymore :stuck_out_tongue:

What do you think about now?

**Comment by gturri** [comment]
Thank you for taking my comments into account. It seems better now (merging the two plugins seems an interesting idea)!

I'll try to find the time to get a deeper look into this patch soon.

**Comment by algorys** [comment]
Just learned about SpecialPattern.
Accordingly, I put hiddenSwitch in SpecialPattern instead of EntryPattern
I also reduced whitespace difference with your last version.

**Comment by gturri** [comment]
I just had a closer look.

First, I find it interesting to merge the two plugins (even if it was not the original purpose of the PR).

On the other hand, I'm not sure I understand what you mean by "For better CSS integration, we need to know (with classes) if the body was displayed or not".
It's probably a noob question (because I'm not a web developer), but I'm not sure I understand why you needed this patch. Do you mean that it's because it's possible to override Dokuwiki's CSS, and in order to take into account this plugin in a relevant way, you needed this refactoring? (if it's the case, can you be more specific?)

To say it differently: can you please explain to me why you needed it, and how it can be useful to this plugin's users?

**Comment by Isammoc** [comment]
jQuery.show (display) only add (remove) `style="display:none"` to the selected elements, no meaning class is added.

We need (I work with @algorys) to know in a CSS way if the element is or not hidden.
Indeed, we override Dokuwiki's CSS to integrate with our company design:
 * headers for hidden elements must be shown as soft link (link to script) with an expandable icon,
 * headers for displayed elements must be shown as clickable small title with an shrinkable icon

To achieve that, we had to modify this plugin as this merge request suggest.

Now, the `hiddenHidden` class is added only when the `hiddenGlobal` contains an hidden body (or is in 'hidden' state).

And, in CSS, we can add a custom icon or override easily:
https://github.com/algorys/hidden/blob/9f3cca4255f2e06008614d29639ad65e4958fc6c/style.css#L40-L42
And with different theme instead of the default theme, we can override more and more.

**Comment by gturri** [comment]
Thanks for those explanations

**Pull request merged**
